version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: attendance_db_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: attendance_db
      TZ: Asia/Seoul
    ports:
      - "3307:3306" # 로컬 테스트용
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: attendance_app_container
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
    # ports: - "8000:8000"  <-- Nginx를 통하므로 외부에 직접 노출할 필요 없음 (주석 처리)
    environment:
      DATABASE_URL: mysql+pymysql://root:1234@db:3306/attendance_db

  nginx:
    image: nginx:latest
    container_name: attendance_nginx
    ports:
      - "80:80" # 웹 기본 포트 (http://inoxde.com)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

volumes:
  db_data: